### ISSUE TITLE
Fix broken image for default logo

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-registry#104]
The [InterMine registry](http://registry.intermine.org/) shows logos for all InterMine instances on the registry. If the mine instance doesn't return a logo, it uses a default InterMine logo. 

This has just broken due to [rawgit](https://rawgit.com) being retired. See all the broken images on the left: 

![image](https://user-images.githubusercontent.com/9271438/46669012-0ef99180-cbc6-11e8-9121-7ae0eb75ffcb.png)

### If you want to pick this task up: 

1. Read through our [contribution guidelines](https://github.com/intermine/intermine-registry/blob/dev/CONTRIBUTING.md)
2. Comment on the issue saying you're picking it up.
2. Clone this repo and set it up locally. You'll need to set up a mongodb, too. There are [in-depth docs](https://docs.google.com/document/d/1ODWOBPA0XePfXmpKN75GQoBPjvFH9Rnp5yIooD1szXw/edit) and a [readme](https://github.com/intermine/intermine-registry#installation) to help you get set up, and you can always mention @yochannah in this issue if you have any more questions. 
3. Replace the broken rawgit images in these two files with a local image stored in _this_ repo (you can download a copy of the logo here: [https://github.com/intermine/design-materials/blob/master/logos/intermine/squareish/45x45.png](https://github.com/intermine/design-materials/blob/master/logos/intermine/squareish/45x45.png)): 
    - https://github.com/intermine/intermine-registry/blob/84fde417d7194484a37cc66e176a5884202c3a5a/public/javascripts/index.js 
    - https://github.com/intermine/intermine-registry/blob/af3635161edf2e5fc698b0e51b30b0e360b17612/public/javascripts/grid.js
4. When you think it's ready, make a pull request! 

### What to do if you need help at any point

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3 no question is too small if you're unsure.

**Comment by CoryWritesCode** [comment]
I'd like to take a crack at it!

**Comment by yochannah** [comment]
@CoryWritesCode awesome! ping me if you have questions at any point

**Comment by CoryWritesCode** [comment]
@yochannah I'm sorry, I'm having trouble getting the mongoDB to connect. I forked then cloned the repo, did `npm i`, `brew install mongodb', and set in my bash `export MONGODB_URL="mongodb://127.0.0.1:27017/"` and when I run `npm start` it hangs on `Listening on port 3000`. Any suggestions? :)

**Comment by yochannah** [comment]
P.S.- if you're interested in an InterMine sticker as thanks, drop me a mail with your physical mailing address at yo@intermine.org and I'll send one over :)
