### ISSUE TITLE
Mine neighbourhoods - trim entries

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-registry#107]
If you enter two entries into the mine neighbourhood section - e.g. `Animals, Microbes`, Microbes will have a space before it in the web service. 

![image](https://user-images.githubusercontent.com/9271438/49222371-921fb280-f3d3-11e8-889b-bc02b638c864.png)

Once we separate by comma it would be nice to trim whitespace off all entries before saving it to the db.

**Comment by yochannah** [comment]
The workaround is to enter `Animals,Microbes` with no spaces.

**Comment by yochannah** [comment]
Opening this ticket up to any contributors who might be interested. 

The application docs are here: https://docs.google.com/document/d/1ODWOBPA0XePfXmpKN75GQoBPjvFH9Rnp5yIooD1szXw/edit# 

## If you want to pick up this task

1. Comment on this issue stating that you intend to work on the task.
2. When you're ready, add your work to the repo and create a pull request. Make sure you comply with our [contributing guidelines](CONTRIBUTING.md). 
3. Bask in glory and email me your address if you'd like to have some InterMine stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by LakshSingla** [comment]
If no one is working on this, I would like to work on this issue.

**Comment by yochannah** [comment]
@LakshSingla please go ahead and pick this up - all your suggestions sound great! 

I don't think there's any specific significance about the updateInstance function not being used so please feel free to go ahead and use it instead if you think it makes sense.

**Comment by yochannah** [comment]
fixed by #114

**Comment by yochannah** [comment]
@LakshSingla I merged this and then realised that for me add instances no longer works :crying_cat_face: does it work for you?

**Comment by LakshSingla** [comment]
@yochannah The last time I looked at it, it was working fine. But that was way back (when I sent the PR). Lemme test it again on my machine and get back to you by tomorrow. Is there any chance it is related to password hashing issue ??

**Comment by yochannah** [comment]
I wondered about that too, but I tried your PR without merging any new
stuff and it was the same. If it's definitely all okay for you let me know.

**Comment by LakshSingla** [comment]
@yochannah So I tested it again on my local machine and it is not working for me too :( . I reverted the change back to before the password hash PR was merged and it is working fine, thus there is some bug in my commit only. Lemme check it and report back to you :)

**Comment by LakshSingla** [comment]
@yochannah Its weird. I tested it again now and it is working. Can you please check again. 
Also what instance were you trying to add ? I removed ThaleMine and added it again. Can you repeat this and see if this is working for you ?

**Comment by yochannah** [comment]
@LakshSingla fyi - I'm pretty sure it was something to do with the refactor that was causing issues. I re-introduced the nice little trim method you'd added and it seems to be working okay now. 

fyi, this is what was happening when I tried to add instances: 

![adding_instnace](https://user-images.githubusercontent.com/9271438/52954169-59afc500-3381-11e9-9411-88014ed8c8cc.gif)

**Comment by LakshSingla** [comment]
@yochannah Ohh !!! Lemme me dig into this tomorrow. As far as I remember, the only thing different in the 2 functions was a hash parameter in the URL. Also, may I know the name of the mine you are trying to add in the GIF. I will use it as a test to check if anything breaks :)

**Comment by yochannah** [comment]
If you haven't started yet, could I get you to hold off for now? I think
some other refactoring is probalby happening in the background in the same
file :D
