### ISSUE TITLE
Update mine display table to link to the mine directly

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine-registry#108]
From Gos:

```
Also, it would be quite nice if one of
the registry columns (the name of the database?) could link directly to the database, not
just pop up an information box with the link.
```

**Comment by yochannah** [comment]
Opening this ticket up to any contributors who might be interested. Visit [http://registry.intermine.org](http://registry.intermine.org) to replicate the issue. 

The application docs are here: https://docs.google.com/document/d/1ODWOBPA0XePfXmpKN75GQoBPjvFH9Rnp5yIooD1szXw/edit# 

## If you want to pick up this task

1. Comment on this issue stating that you intend to work on the task.
2. When you're ready, add your work to the repo and create a pull request. Make sure you comply with our [contributing guidelines](CONTRIBUTING.md). 
3. Bask in glory and email me your address if you'd like to have some InterMine stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by flaredragon** [comment]
Hey I would like to work on this issue!
I wanted to be sure about the functionality that right now clicking on the registry entry pops up the modal.
If the link is added to the name we would want the to not open the modal and directly redirect to the database.

**Comment by yochannah** [comment]
@flaredragon exactly, that sounds right! Please go ahead and pick up the issue :)

Another alternative might be to have a "visit mine" link in one of the columns.
