### ISSUE TITLE
Add maintainer contact details to each mine entry

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-registry#109]
## Task: 

It would be nice for us to know who to contact from a given InterMine, if there is a problem. Let's add two more fields to each InterMine entry:
1. maintainer contact email address (this issue)
2. [maintainer github repository](#93 ) (issue 93, can be tackled at the same time). 

(Note re privacy - if people don't want their personal emails to be public I'd suggest they used a generic/group mail address, e.g. contact@some-domain.com or info@ etc... )

You can take a look at a previous PR to add fields to the registry: https://github.com/intermine/intermine-registry/issues/73 - and docs are here: https://docs.google.com/document/d/1ODWOBPA0XePfXmpKN75GQoBPjvFH9Rnp5yIooD1szXw/edit# 

## If you want to pick up this task

1. Comment on this issue stating that you intend to work on the task.
2. When you're ready, add your work to the repo and create a pull request. Make sure you comply with our [contributing guidelines](CONTRIBUTING.md). 
3. Bask in glory and email me your address if you'd like to have some InterMine stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by himanshukumar660** [comment]
Hello Yo,

I would like to work up on this issue. Could you please assign me this issue. Thanks

**Comment by yochannah** [comment]
Hey @himanshukumar660 - So nice to see you again!! :) GitHub only allows assignees if they're members of the repository in question - but please feel free to pick this issue up and consider it yours 

Yo

**Comment by himanshukumar660** [comment]
Thanks,  working on it.

**Comment by himanshukumar660** [comment]
This issue is solved in PR #113 .

**Comment by vandnakapoor19** [comment]
Hey @yochannah , I'm Outreachy 2020 Applicant and want to solve the issue.
Thanks

**Comment by yochannah** [comment]
Hey @vandnakapoor19 - it looks like this issue is sovled and we can close it already actually, but thanks for volunteering! 💖

**Comment by vandnakapoor19** [comment]
ok, Thanks!
