### ISSUE TITLE
Better initialisation docs - I can't figure out how to populate mines

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-registry#112]
There are some [docs in the readme](https://github.com/intermine/intermine-registry#installation) showing how to run the initregistry.js setup script, but I can't get it to run correctly for me and I'm guessing I've set something up wrong with my mongo instance, maybe. Others in our GSoC chat have had the same problem. 

It would be nice to have a step-by-step db user setup doc, so we're clear on the exact syntax required. (If anyone *has* figured this out please let me know!) 

@danielabutano @lkuffo can either of you help? :)

**Comment by LakshSingla** [comment]
@yochannah I faced the same difficulty in updating `initRegistry.js`. The problems are these:
 - The function which populates the database shows `[Minename] added` even if there is an error ([L62-L64](https://github.com/intermine/intermine-registry/blob/151992915f0fd48b777f68a2ac0fcd6f52023a52/initRegistry.js#L62-L64) which is a major source of confusion. 
- Even on removing this behavior, running the script again would fail to detect an error if the user is not added to the database (hence authentication error, which would not be captured by the `err` parameter).
- There is no way to register a user (This is the major design flaw I found in the code). I had to populate mongo's database myself.

Now possible workarounds would be
- (Temporary) Create a temporary user and run `initRegistry.js` with that user (can be done in a variety of ways).
- (Permanent) Create a register endpoint

**Comment by LakshSingla** [comment]
Alright @yochannah. One thing to take care though is that the default user is removed immediately after populating the script so that no one could misuse it. Also, the password and username of the default user be not hardcoded, but specified (using environment variables maybe), so that even if the default user is not removed (by accident), then no one from outside be able to misuse the user.

**Comment by yochannah** [comment]
Fixed by #129
