### ISSUE TITLE
Remove `/namespace` from the list of authorisation endpoints

### ISSUE THREAD

**Issue by LakshSingla** [intermine/intermine-registry#125]
Currently `GET /namespace` is listed as an authorization required endpoint, which is not the case.

Moreover, I suspect, same is the case for `GET /{namespace}` endpoint. Please, fix `swagger.json` to reflect the nature of the endpoints correctly.

**Comment by bistaastha** [comment]
Hi. Can I work on this?

**Comment by jshreyans** [comment]
Is this still being worked on or up for grabs? @bistaastha

**Comment by itolimaesther** [comment]
Hi @yochannah , I'm an outreachy applicant for May 2020. Please I will love to contribute to this issue.

**Comment by lape15** [comment]
Hello, I am  an outreachy aplilicant for this May 2020, and I would love an opportunity to contribute to this issue?

**Comment by lelouchB** [comment]
Hey @yochannah , I'm also Outreachy Applicant and want to solve this issue..
Thanks
