### ISSUE TITLE
og-expander: For long instance's title, there is overlapping.

### ISSUE THREAD

**Issue by ankitskvmdam** [intermine/intermine-registry#133]
![overlapping](https://user-images.githubusercontent.com/22586210/67034224-ec814900-f134-11e9-9210-00aa85fd1aca.jpg)
Title (maybe Icon for some cases) and the cross button overlaps. This is only on small screen.

**Comment by yochannah** [comment]
fixed by https://github.com/intermine/intermine-registry/pull/134
