### ISSUE TITLE
The update instance page doesn't show maintener email and github url

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-registry#136]
When you try to update an instance, the form doesn't show the maintener email and github url

**Comment by raghav4** [comment]
@danielabutano I've fixed this issue, here's the link to the PR https://github.com/intermine/intermine-registry/pull/143#pullrequestreview-347251241 , also added the troubleshooting tips as discussed with @yochannah . Kindly look into it.

**Comment by raghav4** [comment]
> When you try to update an instance, the form doesn't show the maintainer email and GitHub URL

Now, the form is showing them.
