### ISSUE TITLE
[easy task if you know js] Update documentation to explain how to initialise the repo 

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-registry#140]
We have a nice "getting started" doc for the InterMine registry, but there is one step missing from the documentation - before you run the `node initRegistry.js` command, you need to edit the initRegistry.js file and add your own username and password, rather than the default one. If you don't, you end up with an authentication error.  

## task: 

(Note: This may be easier to do if you run through the "getting started" file yourself, but it is not mandatory.)

1. Take a look at : https://github.com/intermine/intermine-registry/blob/dev/initRegistry.js#L42 to see the lines that need to be edited
2. Update https://github.com/intermine/intermine-registry/blob/dev/getting-started.md#finally-populate-the-database-with-some-intermines to include a step guiding a first-time-user to add the correct username/password. 

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :) @ankitskvmdam may also be able to help out if I'm not around ✨

**Comment by JosephBadua** [comment]
Hello. May I work on this task?

**Comment by ankitskvmdam** [comment]
@JosephBadua Yeah, sure.

**Comment by JosephBadua** [comment]
#142 
I submitted a pull request with the changes. I'd be happy to make any more changes to it if necessary.

**Comment by ankitskvmdam** [comment]
@JosephBadua It seems good.

**Comment by ankitskvmdam** [comment]
@JosephBadua  It would be nice if you use javascript instead of bash. Overall it seems good.

**Comment by JosephBadua** [comment]
I made the change to line 49, added it and committed it.

**Comment by yochannah** [comment]
fixed by #142 - thanks @JosephBadua for making this change and @ankitskvmdam for helping out. 🥇  

@JosephBadua if you are interested in any of our other issues, either in this registry repo or http://intermine.org/contributing/tickets-to-try/, feel free to comment / help out 👍
