### ISSUE TITLE
DELETE /instances/{instancesId} endpoint throws an error even after removing the instance from the database

### ISSUE THREAD

**Issue by dmahajan980** [intermine/intermine-registry#146]
While running some tests for the `DELETE /instances/{instancesId}` the app throws the following error:
![delete error](https://user-images.githubusercontent.com/37256767/74133979-ae41f500-4c0f-11ea-8cab-e7ba4baafb2c.png)

On observing the database, the instance for which the request was made seemed to have been removed successfully from the database. 

I think that we are trying to store the _no of items removed from the database_ inside of `n_removed` which seems to be done in an incorrect manner. Because when I log the `info` object to the console, the console shows the following key-value pairs:
![key-value](https://user-images.githubusercontent.com/37256767/74134408-8901b680-4c10-11ea-8566-fb841a3f2abd.png)

**Comment by yochannah** [comment]
hey @dmahajan980! 

Could you perhaps set up a minimal set of lines to reproduce this? e.g. create an instance then delete it, so we can try copying/pasting this? 

(this would also make a great unit test!)

**Comment by dmahajan980** [comment]
@yochannah I have written a test case for this while writing the tests for issue #118 
The above screenshot is a result of that. However the test code pertaining to this is as follows:

```
const request = require('supertest');
const app = require('../app');

const userOne = {
    user: 'dmahajan980',
    password: 'asdfghj'
};

const flyMine = {
    "name": "FlyMine",
    "namespace": "flymine",
    "neighbours": [
      "MODs"
    ],
    "organisms": [
      "Drosophila"
    ],
    "url": "http://www.flymine.org/query",
    "description": "FlyMine is an integrated database of genomic, expression and protein data for Drosophila, Anopheles and C. elegans",
    "location": {
      "latitude": "52.2003399",
      "longitude": "0.120109"
    },
    "twitter": "@intermineorg"
};

test('POST /instances : Should add an instance to the InterMine Registry', async () => {
    await request(app).post('/service/instances/')
        .auth(userOne.user, userOne.password)
        .send(flyMine)
        .expect(201);
});

test('DELETE /instances : Should delete the given InterMine Registry instance only', async () => {
    await request(app).delete('/service/instances/1')
        .auth(userOne.user, userOne.password)
        .send()
        .expect(200);
});
```

Written using **jest** and to be placed in the `tests/` directory. Please let me know if I should send the code in some other way.

**Comment by dmahajan980** [comment]
@yochannah I ran the above test file and by modifying the DELETE router code on line no. 107, it seems to work fine.
Initially one of the test case fails as expected:
![test fail](https://user-images.githubusercontent.com/37256767/74248664-ee879d00-4d0d-11ea-92cc-5333f07a3b2b.png)

This is the currently existing code for the DELETE /instances/{instancesId} endpoint:
![fail route](https://user-images.githubusercontent.com/37256767/74248343-74efaf00-4d0d-11ea-998e-424dbbfedd3f.png)

Notice when I simply change the code on line no. 107 as follows
![pass_route](https://user-images.githubusercontent.com/37256767/74248448-9781c800-4d0d-11ea-8b6f-2891a1cc9e81.png)

This code passes both the above mentioned test cases as shown below:
![pass](https://user-images.githubusercontent.com/37256767/74250616-e0874b80-4d10-11ea-8167-b9dbd5328882.png)

This is just a simple change. But I wanted to bring another issue to your notice with the route handlers. Most of the REST API methods such as `find()`, `remove()` which are used inside of route handlers are deprecated, as shown in the terminal:
![dep](https://user-images.githubusercontent.com/37256767/74250306-6a82e480-4d10-11ea-811a-a2bead01b613.png)

Shall I update all of the methods and send a combined pull request along with the fix for this currently open issue? Or do I create a separate issue for it and send a separate pull request?

Thank you :smile:
