### ISSUE TITLE
Request: automatically synchronise new instances

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-registry#38]
I've added instances to the registry via the UI a couple of times. Both times they don't show up until I manually synchronise them. 

It might be better to automatically sync new instances?

**Comment by danielabutano** [comment]
The instances were Flymine beta and HumanMine Beta. They override the FlyMine and HumanMine. Fixed [here](https://github.com/intermine/intermine-registry/commit/08a1f543f0160e7c182b67410ae2a240d1b8bdc6)
