### ISSUE TITLE
Add custom fields to registry - maintainer name and url 

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-registry#73]
We'd like to add the option to include the maintainer organisation of any given intermine and a link to their site, eg. the json properties for flymine or humanmine might look like this: 

```
maintainerOrgName : "InterMine core team, Micklem Lab",
maintainerUrl : "http://intermine.org/"
```
(from https://github.com/intermine/intermine/issues/1751)

See also the registry docs here: https://docs.google.com/document/d/1ODWOBPA0XePfXmpKN75GQoBPjvFH9Rnp5yIooD1szXw/edit# 

cc @danielabutano @amand1996

**Comment by julie-sullivan** [comment]
@danielabutano Can I reopen this ticket? I think it would be useful to have organisation name and url.

**Comment by danielabutano** [comment]
@julie-sullivan We have already maintener name and url, click for example, on PythoMine.
I don't understand your request, do you want to rename these fields@ or do you want to add 2 more?

**Comment by julie-sullivan** [comment]
@danielabutano Whoops! No, that's what I need. I didn't read. Thanks!
