### ISSUE TITLE
Add print stylesheet with aim to fit everything on one A4 page

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-registry#74]
The InterMine Registry is pretty awesome. When we go to conferences it would be nice to print out a few sheets containing a list of *all* the InterMines, straight from the registry. 

We'd need to show the following fields: 
- top of page:  
  - header (e.g. "InterMine Registry")
  - registry URL (Note: URLs can be extracted from the href value using css pseudo-elements and `attr()`, like this: http://jsbin.com/fekanow/edit?html,css,output )
- Once per intermine:
  - mine name (e.g. "BovineMine")
  - organisms found in each mine
  - ideally URL of each mine if it fits? 

The end goal of this exercise is to make this a nice, compact sheet that people interested in InterMine can visually scan to see if their favourite organism is present, and if so, where to go to find it. 

More info on print stylesheets: https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/

**Comment by amand1996** [comment]
[file.pdf](https://github.com/intermine/intermine-registry/files/1699507/file.pdf)
Hey @yochannah ! I think something of this sort should work.

**Comment by yochannah** [comment]
@amand1996 This looks pretty good! One question though: I think some of the organisms might be missing?

**Comment by yochannah** [comment]
Actually, a couple of further thoughts: 

- It might be hard to read when all the organisms are there. Can we do stripes on alternate rows and/or lines between each row?
- if sans serif is possible and doesn't make things overflow, it might be nicer to use an arial or helvetica font. (Just thinking to add as much aesthetic value as possible since this mightbe handed out at booths in conferences!) I know these fonts can be wider so it might not work.

**Comment by amand1996** [comment]
[file.pdf](https://github.com/intermine/intermine-registry/files/1700057/file.pdf)
@yochannah Well, this might work. I have added some random organisms just for testing the overflow thing. I dont think any organism is missing there. I have also changed the font to sans serif. Borders also done. :)

**Comment by amand1996** [comment]
I still don't know whether it would fit in a single page after all organisms are put in it. Maybe will have to check it with the actual data from the production DB.
