### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by kunal-mohta** [intermine/intermine-registry#79]
On following the instructions as given in the `README.md` of the repo, I faced the following MongoDB error when I did `npm start`
![screenshot 2018-02-14 18 54 55](https://user-images.githubusercontent.com/30414954/36206592-eaee432a-11b8-11e8-9fdf-f7f2b52597d4.png)

Can someone help me?
Did I get something wrong?

**Comment by amand1996** [comment]
You will have to add the local mongodb database to the environment variables.
We are currently under the process of updating the docs. Kindly view these instructions for running the app.

https://github.com/amand1996/intermine-registry/tree/temp

**Comment by kunal-mohta** [comment]
I am looking forward to work on the Intermine's GSOC'18 Project Ideas **Cross-InterMine search tool**
and **Data browser tool**. 
Am I at the right place?

**Comment by kunal-mohta** [comment]
![screenshot 2018-02-15 00 20 10](https://user-images.githubusercontent.com/30414954/36222111-472778a0-11e6-11e8-9313-c963ba0e1b84.png)

I am not sure if this is dumb question or not, but in the MongoDB database that I am going to provide with a `users` collection, where should I set the variables for *a) Your application host b) Username in the DB c) Password of the entered username* as mentioned in the link you provided.

I think that is the reason why I am getting this error(?)

**Comment by amand1996** [comment]
The user and password is required only to make an account for logging into the intermine-registry for getting admin access. That would allow you to add, edit and delete intermines from the registry. You just need to insert a document to the `users` collection with the following format:
```
{
    "user": "abc",
    "password": "def123"
}
```

**Comment by kunal-mohta** [comment]
I actually did the same. Here is a screenshot of my **users** collection
![screenshot 2018-02-15 00 34 39](https://user-images.githubusercontent.com/30414954/36222719-45b88638-11e8-11e8-81de-9d1155d03067.png)

I am using [mLab](https://mlab.com/) as a **Database-as-a-service** for MongoDB

**Comment by amand1996** [comment]
Then, maybe you are not setting up the environment variables correctly. Something of this sort should work for you. You can get this url from your mlab account.

`$ export MONGODB_URL="mongodb://username:password@ds125068.mlab.com:25068/intermine"`

**Comment by kunal-mohta** [comment]
Okay.. 
I got it working.
Thanks for helping me. 😄 

I would like to suggest you to add to the **README.md** that the server is running on the `port 3000`
I know it is the default port of ExpressJS because I have worked with it before, but many other developers might not know it 😅

**Comment by amand1996** [comment]
Thanks for your suggestion. I have added your suggested point to the existing PR. :)
