### ISSUE TITLE
automatic upload mechanism for the versions

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-registry#8]
All data related to the versions should be updated every 24 h using the existing endpoints

**Comment by danielabutano** [comment]
Not closed yet @lkuffo. I have added betaflymine instance to test it. Updated api and version releases with wrong data. i will check tomorrow that the fields have been updated.

**Comment by danielabutano** [comment]
@lkuffo I think that FlymineBeta, instance created to test the automatic mechanism, hasn't been updated :(

**Comment by danielabutano** [comment]
To be tested after we upgrade to the hobby version

**Comment by danielabutano** [comment]
I have updated in FlyMine beta instance, the "release_version" field to "beta-test", in order to verify that the automatic update mechanism works properly

**Comment by lkuffo** [comment]
I think it worked! 👍

**Comment by lkuffo** [comment]
I think it works! 👍
