### ISSUE TITLE
Icon Missing http://registry.intermine.org/

### ISSUE THREAD

**Issue by omi10859** [intermine/intermine-registry#80]
![screen shot 2018-02-22 at 5 16 53 pm](https://user-images.githubusercontent.com/26123416/36536848-68362212-17f4-11e8-962a-1137d01301ec.png)

**Comment by MananAgarwal** [comment]
Icon "https://phytozome.jgi.doe.gov/intermine/cdn/img/Phytozome-logo-small.png" does not exist. There is not /img folder.
![image](https://user-images.githubusercontent.com/24625562/36541711-c370df04-1804-11e8-8127-8a2d605102e4.png)

**Comment by julie-sullivan** [comment]
@JoeCarlson Thanks for adding your mines to the registry! However, the logos aren't showing up properly. Is the path correct?

**Comment by JoeCarlson** [comment]
sorry about that. we rolled out a new release. I really don't understand why we (again) have this problem with our CDN.

**Comment by yochannah** [comment]
This has been fixed. Thanks @JoeCarlson !

**Comment by yochannah** [comment]
![image](https://user-images.githubusercontent.com/9271438/37146443-a2ac318a-22bb-11e8-9099-890684a59464.png)

**Comment by yochannah** [comment]
@JoeCarlson fyi, this has popped up again for phytomine and bmap...

**Comment by JoeCarlson** [comment]
yeah. Thanks for letting me know. We've been reworking our deployment processes and it looks like something got dropped. Again. We've fixed it again. So we'll be good for a while.
