### ISSUE TITLE
If no results are found no Fallback Message is given

### ISSUE THREAD

**Issue by flaredragon** [intermine/intermine-registry#82]
Issue: If no result for a pirticular mine is found no error message or fallback message is given

Screenshot:
![screenshot from 2018-02-28 21-54-06](https://user-images.githubusercontent.com/29121452/36799036-2d16c014-1cd2-11e8-874a-b9e080c67185.png)

I would like to work on this.

**Comment by yochannah** [comment]
Opening this ticket up to any contributors who might be interested. 

The application docs are here: https://docs.google.com/document/d/1ODWOBPA0XePfXmpKN75GQoBPjvFH9Rnp5yIooD1szXw/edit# 

## If you want to pick up this task

1. Comment on this issue stating that you intend to work on the task.
2. When you're ready, add your work to the repo and create a pull request. Make sure you comply with our [contributing guidelines](CONTRIBUTING.md). 
3. Bask in glory and email me your address if you'd like to have some InterMine stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by flaredragon** [comment]
Hey @yochannah I've worked on this issue would like your feedback.

**Comment by yochannah** [comment]
@flaredragon Awesome, thanks for picking this up! I will review this as soon as I've figured out how to populate the registry on my instance https://github.com/intermine/intermine-registry/issues/112 - I don't suppose you remember how you got it working? :laughing:

**Comment by flaredragon** [comment]
Oh funny thing another contributor emailed me about the same issue he faced.I mailed the procedure to him I'll paste it below - 

Firstly export MONGODB_URL wasn't working in my laptop for some reason hence I replaced process.env.MONGODB_URL in code with my db url.It was probably in the models folder.

Secondly I edited the user model file to automatically insert an user upon model creation/You could create an users collection in mongo directly and register an entry with the username and password you wish to use. 

Third, I edited the initRegistry file and added the host url(http://localhost:3000 username and password fields(the same we entered into the DB above) and ran this file as a seperate node process. 
node initRegistry.js

Finally then I started the server.(npm run start) 

PS - It also took me an hour to figure out the same.

Could I open an PR to update the documentation for the same?
