### ISSUE TITLE
Error returned when number of instances returned by the query is zero

### ISSUE THREAD

**Issue by arunans23** [intermine/intermine-registry#85]
While searching for mines in the registry, if query returns an empty set, the status code is set to 404 which gives an error in chrome console.

For example if you click on the following link, it returns a status code of 404.
[http://registry.intermine.org/service/instances/?q=abc](http://registry.intermine.org/service/instances/?q=abc)

Returning an empty query is not an error and it should be returned with a 200 status code.

[Here](https://github.com/intermine/intermine-registry/blob/dev/routes/instances.js#L59), the if condition, checking for empty set should be removed.
```
if (instances.length === 0){
            api_response.statusCode = 404;
}
```

**Comment by danielabutano** [comment]
Merge PR. Thnaks
