### ISSUE TITLE
Overlapping buttons in mobile

### ISSUE THREAD

**Issue by sarthak-sehgal** [intermine/intermine-registry#87]
## Description
The "Visit website" button is overlapping with the "Organisms" in mobile at a few places.

## Screenshot
![intermine 3](https://user-images.githubusercontent.com/29003134/37874462-3f2b3602-304d-11e8-921f-fd1297299f5a.png)

@yochannah, shall I work on this if it is an appropriate issue?

**Comment by yochannah** [comment]
Sarthak: go ahead! :) We have a lot of PRs to review so it might not be
merged really fast, but it would still be great! :)

**Comment by sarthak-sehgal** [comment]
@yochannah I am facing some issues in setting up the environment. I'll send a PR by this weekend. Really sorry for the delay.

**Comment by yochannah** [comment]
No worries Sarthak :)

**Comment by yochannah** [comment]
Adding a help wanted label - world in general, feel free to pick this issue up if it interests you. 

Application docs are here: https://docs.google.com/document/d/1ODWOBPA0XePfXmpKN75GQoBPjvFH9Rnp5yIooD1szXw/edit# 

## If you want to pick up this task

1. Comment on this issue stating that you intend to work on the task.
2. When you're ready, add your work to the repo and create a pull request. Make sure you comply with our [contributing guidelines](CONTRIBUTING.md). 
3. Bask in glory and email me your address if you'd like to have some InterMine stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by aaryan01** [comment]
Hi, can I work on this issue?

**Comment by yochannah** [comment]
@aaryan01 Go ahead! :)

**Comment by himanshukumar660** [comment]
@aaryan01 Are you still working on this?

**Comment by aaryan01** [comment]
@himanshukumar660 You can work on it if you want.

**Comment by himanshukumar660** [comment]
Okay, Thanks for informing.

**Comment by yochannah** [comment]
Fixed by https://github.com/intermine/intermine-registry/pull/134
